#!/usr/bin/env bash

javac ./*.java



#java Main < data/bht.txt
echo "Some should return true"
java Main -q< handmade/K3-2.txt

echo "Some should return False"
java Main -q < handmade/K3-2.txt
#java Main < testSome.txt
#java Main --args test

rm *.class

